<a href="https://colab.research.google.com/github/Maher1410/NN-LABS/blob/main/Lab_6_Regularization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/LABNN/telco_churn.csv')
print(df.head())
df.info()

   customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No
1  5575-GNVDE    Male              0      No         No      34          Yes
2  3668-QPYBK    Male              0      No         No       2          Yes
3  7795-CFOCW    Male              0      No         No      45           No
4  9237-HQITU  Female              0      No         No       2          Yes

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No
1                No             DSL            Yes  ...              Yes
2                No             DSL            Yes  ...               No
3  No phone service             DSL            Yes  ...              Yes
4                No     Fiber optic             No  ...               No

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes
1          No          No              No        One year               No
2          No          No              No  Month-to-month              Yes
3         Yes          No              No        One year               No
4          No          No              No  Month-to-month              Yes

               PaymentMethod MonthlyCharges  TotalCharges Churn
0           Electronic check          29.85         29.85    No
1               Mailed check          56.95        1889.5    No
2               Mailed check          53.85        108.15   Yes
3  Bank transfer (automatic)          42.30       1840.75    No
4           Electronic check          70.70        151.65   Yes

[5 rows x 21 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [2]:
df['TotalCharges'] = df['TotalCharges'].replace(' ', np.nan)
df['TotalCharges'] = df['TotalCharges'].astype('float')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [3]:
import numpy as np

df['Churn'] = np.where(df['Churn'] == 'Yes', 1, 0)

def convert_categories(cat_list):
    for col in cat_list:
        df[col] = df[col].astype('category')
        df[f'{col}_cat'] = df[f'{col}'].cat.codes

category_list = ['gender', 'Partner', 'Dependents', 'PhoneService',
                 'MultipleLines', 'InternetService',
                 'OnlineSecurity', 'OnlineBackup',
                 'DeviceProtection', 'TechSupport', 'StreamingTV',
                 'StreamingMovies', 'Contract', 'PaperlessBilling',
                 'PaymentMethod']
convert_categories(category_list)

print(df.head())
df['TotalCharges']

   customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No
1  5575-GNVDE    Male              0      No         No      34          Yes
2  3668-QPYBK    Male              0      No         No       2          Yes
3  7795-CFOCW    Male              0      No         No      45           No
4  9237-HQITU  Female              0      No         No       2          Yes

      MultipleLines InternetService OnlineSecurity  ... InternetService_cat  \
0  No phone service             DSL             No  ...                   0
1                No             DSL            Yes  ...                   0
2                No             DSL            Yes  ...                   0
3  No phone service             DSL            Yes  ...                   0
4                No     Fiber optic             No  ...                   1

  OnlineSecurity_cat OnlineBackup_cat DeviceProtection_cat TechSupport_cat  \
0                  0                2                    0               0
1                  2                0                    2               0
2                  2                2                    0               0
3                  2                0                    2               2
4                  0                0                    0               0

  StreamingTV_cat StreamingMovies_cat Contract_cat  PaperlessBilling_cat  \
0               0                   0            0                     1
1               0                   0            1                     0
2               0                   0            0                     1
3               0                   0            1                     0
4               0                   0            0                     1

   PaymentMethod_cat
0                  2
1                  3
2                  3
3                  0
4                  2

[5 rows x 36 columns]

0         29.85
1       1889.50
2        108.15
3       1840.75
4        151.65
         ...
7038    1990.50
7039    7362.90
7040     346.45
7041     306.60
7042    6844.50
Name: TotalCharges, Length: 7043, dtype: float64

In [9]:
X = df[['gender_cat', 'Partner_cat', 'Dependents_cat', 'PhoneService_cat', 'MultipleLines_cat',
        'OnlineSecurity_cat', 'OnlineBackup_cat', 'DeviceProtection_cat', 'TechSupport_cat',
        'StreamingMovies_cat', 'Contract_cat', 'PaperlessBilling_cat', 'PaymentMethod_cat',
        'TotalCharges', 'SeniorCitizen', 'tenure']]

y= df['Churn']

In [10]:
seed = 7
np.random.seed(seed)

from sklearn.model_selection import train_test_split

X_train, X_test_hold_out, y_train, y_test_hold_out = train_test_split(X, y, test_size=0.2, random_state=seed)
X_train

,gender_cat,Partner_cat,Dependents_cat,PhoneService_cat,MultipleLines_cat,OnlineSecurity_cat,OnlineBackup_cat,DeviceProtection_cat,TechSupport_cat,StreamingMovies_cat,Contract_cat,PaperlessBilling_cat,PaymentMethod_cat,TotalCharges,SeniorCitizen,tenure
2338,1,1,1,1,0,1,1,1,1,1,2,0,0,1322.85,0,72
4705,1,0,0,1,0,2,2,0,0,0,0,1,2,494.95,0,6
3514,1,1,1,1,2,2,0,2,2,2,2,1,2,6586.85,0,60
1549,1,0,0,1,0,0,0,0,0,0,0,1,3,45.85,0,1
5757,0,1,0,1,2,1,1,1,1,1,0,0,3,734.60,1,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5699,1,0,0,1,0,0,0,2,0,0,0,0,2,1219.85,0,15
2550,0,1,1,1,0,1,1,1,1,1,2,0,3,1090.10,0,56
537,0,1,1,1,0,2,2,2,0,0,1,1,3,1955.40,0,33
1220,1,0,0,1,2,2,0,0,0,2,0,0,0,1111.20,0,17
4271,0,1,1,1,0,1,1,1,1,1,1,0,3,543.00,0,28

In [11]:
X_train = np.asarray(X_train).astype(np.float32)
y_train = np.asarray(y_train).astype(np.float32)

X_test_hold_out = np.asarray(X_test_hold_out).astype(np.float32)
y_test_hold_out = np.asarray(y_test_hold_out).astype(np.float32)

In [12]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.metrics import accuracy_score

model = Sequential()
model.add(Dense(X_train.shape[1], input_shape=(X_train.shape[1],), kernel_initializer='normal', activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='softmax'))
model.compile(optimizer = 'adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=20)

Epoch 1/20
177/177 [==============================] - 3s 6ms/step - loss: nan - accuracy: 0.7238
Epoch 2/20
177/177 [==============================] - 1s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 3/20
177/177 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 4/20
177/177 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7371
Epoch 5/20
177/177 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 6/20
177/177 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7371
Epoch 7/20
177/177 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7371
Epoch 8/20
177/177 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7371
Epoch 9/20
177/177 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7371
Epoch 10/20
177/177 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7371
Epoch 11/20
177/177 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7371
Epoch 12/20
177/177 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7371
Epoch 13/20
177/177 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7371
Epoch 14/20
177/177 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7371
Epoch 15/20
177/177 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7371
Epoch 16/20
177/177 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7371
Epoch 17/20
177/177 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 18/20
177/177 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 19/20
177/177 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 20/20
177/177 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7371

In [13]:
y_pred = model.predict(X_test_hold_out)
y_pred = np.where(y_pred > 0.5, 1, 0)
print("Accuracy: ", accuracy_score(y_pred, y_test_hold_out))

45/45 [==============================] - 0s 2ms/step
Accuracy:  0.7246273953158269

In [14]:
from tensorflow.keras import regularizers

model_lasso = Sequential()
model_lasso.add(Dense(X_train.shape[1], input_shape=(X_train.shape[1],), kernel_initializer='normal', activation='relu', kernel_regularizer=regularizers.l1(1e-6)))
model_lasso.add(Dense(32, activation='relu'))
model_lasso.add(Dense(32, activation='relu'))
model_lasso.add(Dense(1, activation='sigmoid'))
model_lasso.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model_lasso.fit(X_train, y_train, epochs=20)

Epoch 1/20
177/177 [==============================] - 2s 3ms/step - loss: nan - accuracy: 0.7290
Epoch 2/20
177/177 [==============================] - 1s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 3/20
177/177 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 4/20
177/177 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 5/20
177/177 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 6/20
177/177 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 7/20
177/177 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 8/20
177/177 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7371
Epoch 9/20
177/177 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7371
Epoch 10/20
177/177 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 11/20
177/177 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7371
Epoch 12/20
177/177 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 13/20
177/177 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7371
Epoch 14/20
177/177 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 15/20
177/177 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 16/20
177/177 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 17/20
177/177 [==============================] - 1s 4ms/step - loss: nan - accuracy: 0.7371
Epoch 18/20
177/177 [==============================] - 1s 5ms/step - loss: nan - accuracy: 0.7371
Epoch 19/20
177/177 [==============================] - 1s 5ms/step - loss: nan - accuracy: 0.7371
Epoch 20/20
177/177 [==============================] - 1s 4ms/step - loss: nan - accuracy: 0.7371

In [15]:
y_pred = model_lasso.predict(X_test_hold_out)
y_pred = np.where(y_pred > 0.5, 1, 0)
print("Accuracy With Lasso: ", accuracy_score(y_pred, y_test_hold_out))

45/45 [==============================] - 0s 2ms/step
Accuracy With Lasso:  0.7246273953158269

In [16]:
model_ridge = Sequential()
model_ridge.add(Dense(X_train.shape[1], input_shape=(X_train.shape[1],), kernel_initializer='normal', activation='relu', kernel_regularizer=regularizers.l2(1e-6)))
model_ridge.add(Dense(32, activation='relu'))
model_ridge.add(Dense(32, activation='relu'))
model_ridge.add(Dense(1, activation='sigmoid'))
model_ridge.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model_ridge.fit(X_train, y_train, epochs=20)

Epoch 1/20
177/177 [==============================] - 1s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 2/20
177/177 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7371
Epoch 3/20
177/177 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7371
Epoch 4/20
177/177 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7371
Epoch 5/20
177/177 [==============================] - 1s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 6/20
177/177 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 7/20
177/177 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7371
Epoch 8/20
177/177 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 9/20
177/177 [==============================] - 1s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 10/20
177/177 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 11/20
177/177 [==============================] - 1s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 12/20
177/177 [==============================] - 1s 4ms/step - loss: nan - accuracy: 0.7371
Epoch 13/20
177/177 [==============================] - 1s 4ms/step - loss: nan - accuracy: 0.7371
Epoch 14/20
177/177 [==============================] - 1s 4ms/step - loss: nan - accuracy: 0.7371
Epoch 15/20
177/177 [==============================] - 1s 6ms/step - loss: nan - accuracy: 0.7371
Epoch 16/20
177/177 [==============================] - 1s 6ms/step - loss: nan - accuracy: 0.7371
Epoch 17/20
177/177 [==============================] - 1s 4ms/step - loss: nan - accuracy: 0.7371
Epoch 18/20
177/177 [==============================] - 1s 3ms/step - loss: nan - accuracy: 0.7371
Epoch 19/20
177/177 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7371
Epoch 20/20
177/177 [==============================] - 1s 3ms/step - loss: nan - accuracy: 0.7371

In [17]:
y_pred = model_ridge.predict(X_test_hold_out)
y_pred = np.where(y_pred > 0.5, 1, 0)
print("Accuracy With Ridge: ", accuracy_score(y_pred, y_test_hold_out))

45/45 [==============================] - 0s 2ms/step
Accuracy With Ridge:  0.7246273953158269